### ISSUE TITLE
Support for Emacs?

### ISSUE THREAD

**Issue by RafalLukawiecki** [cyberkov/openhab-vim#10]
Do you plan, or do you already have, any support for the OpenHAB/Xtend syntax highlighting in Emacs? Many thanks.

**Comment by cyberkov** [comment]
Hello! 
I am sorry but I do not use emacs (see https://en.m.wikipedia.org/wiki/Editor_war ;-)). 
But I am sure you could extract the keywords from the syntax file (or use the original file from the openHAB editor which will be more accurate but harder to read) to build it for emacs :-)

Cheers Hannes

**Comment by RafalLukawiecki** [comment]
Thank you, Hannes. I am well aware of the "war". I have been using Vi/Vim for about 30 years and Emacs only very recently, only a few months. There is a new mode in it, called, Evil, which brings Vim to a much more programmable editor. :) I keep using all Vim keystrokes etc. Worth a look.

I will try to convert your files to Emacs...sometime!
