### ISSUE TITLE
Missing syntax for .things

### ISSUE THREAD

**Issue by mueller-ma** [cyberkov/openhab-vim#7]
I started here: https://github.com/mueller-ma/openhab-vim/tree/patch-2
I have some problems to add the thing name to a catergory (e.g. astro:sun:home).
Having a list with all options for the first two strings is not an option, because there are so many bindings.
I tried it with match: " *:*:* " but that doesn't work

**Comment by cyberkov** [comment]
Fixed with #8 i think :-)
